export const env = {
  PUBLISHABLE_CLERK_KEY: process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY,
  DATABASE_URL: process.env.DATABASE_URL,
  SERVER_URL: process.env.EXPO_PUBLIC_SERVER_URL,
  GEOAPIFY_API_KEY: process.env.EXPO_PUBLIC_GEOAPIFY_API_KEY,
  GOOGLE_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_API_KEY,
  PUBLISHABLE_STRIPE_KEY: process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  SECRET_STRIPE_KEY: process.env.STRIPE_SECRET_KEY,
};
